version: "3.9"
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "jack"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    depends_on:
      - "database"
    ports: 
      - "9000:9000"
  web:
    build: .
    depends_on:
      - "api"
    ports:
      - "3000:3000"
volumes:
  pgdata:
